<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<Authors>Alcazar Security</Authors>
		<description>
			Alcazar.DevExpress.TagHelpers contains tag helpers and other extensions for DevExpress ASP.Net Core controls.
			This assembly depends on the Alcazar ASP.Net One framework, which is a licensed product.
			This assembly depends on DevExpress components, which are licensed products, and are not supplied by Alcazar.
		</description>
		<Copyright>Copyright © Alcazar 2007-2024</Copyright>
		<PackageIcon>alcazar-2020-45.png</PackageIcon>
		<PackageTags>Alcazar Web DevExpress DevExtreme ASP.Net Core</PackageTags>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageLicenseFile>alcazar-license.md</PackageLicenseFile>
		<PackageLicenseExpression></PackageLicenseExpression>
		<PackageProjectUrl>http://www.alcazarsecurity.com/projects/Alcazar.Web</PackageProjectUrl>
		<PackageReleaseNotes></PackageReleaseNotes>
		<PackageIconUrl />
		<PackageId>Alcazar.DevExpress.TagHelpers</PackageId>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

  <ItemGroup>
    <Compile Remove="TagHelpers\Contained\ContainedItemContentTagHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\" />
    <Folder Include="Extensibility\" />
    <Folder Include="TagHelpers\Reports\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\A\_solution\alcazar-2020-45.png" Link="alcazar-2020-45.png">
      <PackagePath></PackagePath>
      <Pack>True</Pack>
    </None>
    <None Include="..\..\A\_solution\alcazar-license.md" Link="alcazar-license.md">
      <PackagePath></PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Formats.Asn1" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\A\Alcazar.Web.Base\Alcazar.Web.Base.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="DevExtreme.AspNet.Core">
      <Version>24.1.6</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="DevExtreme.AspNet.Core">
      <Version>24.2.7</Version>
    </PackageReference>
  </ItemGroup>

</Project>
